name: CI

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: client/package.json
      - uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: server/pyproject.toml
      - run: make check

  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: client/package.json
      - uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: server/pyproject.toml
      - run: make build

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: client/package.json
      - uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: server/pyproject.toml
      - run: make tests
